name: Repo1workflow
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          echo test
      - name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PATHOOK }}
          repository: weide-zhou/ticket16
          event-type: check
